apache/maven-parent

- doxia-tools/src/site-docs/site.xml
- doxia-tools/src/site/site.xml
- maven-archetype-bundles/src/site-docs/site.xml
- maven-plugins/src/site-docs/site.xml
- maven-plugins/src/site/site.xml
- maven-shared-components/src/site-docs/site.xml
- maven-shared-components/src/site/site.xml
- maven-skins/src/site-docs/site.xml
- maven-skins/src/site/site.xml
- src/site-docs/site.xml
- src/site/site.xml
> Update site.xml namespace to 1.8.0

- pom.xml
> add elharo to committers list

- pom.xml
@hboutemy The comment is both wrong and redundant with the properties.
> docs: remove out of date comment

- pom.xml
> [MPOM-252] remove broken mail list archives

- pom.xml
It's helping to investigate failed tests on CI
> [MPOM-276] streamLogsOnFailures for maven-invoker-plugin as default

- pom.xml
take version of maven-plugin-plugin from parent
> [MPOM-292] cleanup after upgrade parent to ASF 25

- src/site/site.xml
Fixes https://issues.apache.org/jira/browse/MPOM-300
Will test with a plugin later.
> [MPOM-300] switch from GA to ASF Matomo.

- doxia-tools/src/site-docs/site.xml
- maven-extensions/src/site-docs/site.xml
- maven-plugins/src/site-docs/site.xml
- maven-shared-components/src/site-docs/site.xml
- maven-skins/src/site-docs/site.xml
- src/site-docs/site.xml
- src/site/site.xml
- add link to Data Privacy
- add / copy ASF section to documentation
> [MPOM-322] Add ASF Data Privacy

- maven-extensions/pom.xml
- maven-plugins/pom.xml
- pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MPOM-350
Raise JDK mimimum requirements to 1.8
Discussion at: https://lists.apache.org/thread/ksqgjw7v3rbzw7pq2pvv8xov38799yok
> [MPOM-350] Raise JDK requirement to 1.8

- maven-plugins/pom.xml
- pom.xml
use javadoc from plugin documentation
> [MPOM-354] leverage new report plugin

- pom.xml
- use new rules file
- remove non existing rules from excludes
> [MPOM-371] Fix checkstyle configuration

- pom.xml
We may want to defer a bit on that one, as it's a disruptive upgrade.
> Bump plexus-utils from 3.5.1 to 4.0.0 and add plexus-xml 4.0.0

- pom.xml
> [MPOM-426] downgrade plexus-xml to 3.0.0 as 4 is incompatible with Maven 3

- pom.xml
https://issues.apache.org/jira/browse/MPOM-447
> [MPOM-447] activate javac's release flag

- pom.xml
It will allow easier to override for testing
> Introduce property for maven-shared-resources version

- pom.xml
Test code should be also checked.
It can discover old issues during update.
> Check test code by checkstyle

- docs/src/site/apt/index.apt.vm
- maven-extensions/pom.xml
- maven-plugins/pom.xml
- maven-shared-components/pom.xml
New property should be used for components documentation targeted to Maven 4
> Introduce property maven4x.site.path

- pom.xml
> Add licenseText to modello

- .asf.yaml
Re-enable notifications (disabled for JIRA import)
> Re-enable notifications (disabled for JIRA import)

- KEYS
this will be easier than trying to read every bits of docs in https://maven.apache.org/developers/release/pmc-gpg-keys.html or https://infra.apache.org/release-signing.html
> add concrete gpg commands to add a key

- .asf.yaml
https://lists.apache.org/thread/d4lgr2x7v3x8b7m0orsmhvzc254yqj2f
> Fix asf.yaml syntax

- .mvn/maven.config
- pom.xml
similar to https://github.com/apache/maven-apache-parent/pull/183
> Move snapshot repositories in a profile

- .asf.yaml
Reverts apache/maven-parent#463
> Enable notifications after migration
